### ISSUE TITLE
Error using Width/Height properties

### ISSUE THREAD

**Issue by vcarbo** [wolfika/vue-playing-card#6]
Hi, I've got the error " Invalid prop: custom validator check failed for prop "width"."
I'm just using 
`<vue-playing-card class="card" :signature="signature" width="300"></vue-playing-card>
`What's the pb please ?

**Comment by wolfika** [comment]
Hi @vcarbo!

The component accepts either a `string` or a `number` value for the `width`/`height` parameters. In your case you're passing the value as string, but the component actually expects strings to end in `px`. (Sorry, the readme contained a wrong example for this, I fixed it immediately.)

So you have 2 options, passing the width as a string:
`<vue-playing-card class="card" :signature="signature" width="300px"></vue-playing-card>`

Or binding it to a number:
`<vue-playing-card class="card" :signature="signature" :width="300"></vue-playing-card>`

Let me know if you need any further help.

**Comment by wolfika** [comment]
v1.0.0 now supports `"300"` as string.
