### ISSUE TITLE
Can't get Card Component to Render

### ISSUE THREAD

**Issue by zcoop98** [wolfika/vue-playing-card#8]
Having some trouble getting the component to render; just added `<vue-playing-card cover />` as a first test, and am getting an error out of `vue-playing-card.min.js`:

```
TypeError: e.component is not a function
    at n (vue-playing-card.min.js?c183:6)
    at resolveAsyncComponent (vue.runtime.esm.js?2b0e:3686)
    at createComponent (vue.runtime.esm.js?2b0e:3200)
    at _createElement (vue.runtime.esm.js?2b0e:3422)
    at createElement (vue.runtime.esm.js?2b0e:3353)
    at vm._c (vue.runtime.esm.js?2b0e:3491)
    at Proxy.render (eval at ./node_modules/cache-loader/dist/cjs.js?
        {"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"43ec0d15-vue-loader-template"}!
        ./node_modules/vue-loader/lib/loaders/templateLoader.js?!
        ./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!
        ./src/components/CardFlip.vue?vue&type=template&id=9c661d66& (app.js:986), <anonymous>:8:21)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3548)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4066)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
```

Am I doing something weird here? Any help would be appreciated!

```
<template>
    <div>
        <vue-playing-card cover />
    </div>
</template>

<script>
import VuePlayingCard from 'vue-playing-card';

export default {
    components: {
        VuePlayingCard,
    },
}
</script>
```

**Comment by zcoop98** [comment]
I've been able to call it in a different project using the script import syntax... something fishy is going on here, and it's probably something with my own project.

**Comment by wolfika** [comment]
@zcoop98 Thanks for the report. It's totally possible that something is wrong with the lib as well, I haven't updated in a while. Some refactoring is long overdue anyway, I will look into it once I have the time. Glad you could get it working though.

**Comment by zcoop98** [comment]
_Finally_ found out what was causing issues. After lots of digging through various errors I was running into (including a cryptic `"TypeError: Vue.component is not a function"`), I finally found reference to wrapping the import with curly braces `{}`. It looks like, when _locally_ importing the component, you need to use:
```
import { VuePlayingCard } from 'vue-playing-card';
```
Rather than:
```
import VuePlayingCard from 'vue-playing-card';
```
Looks like we're in business now!
